"""empty message

Revision ID: 9176ecf6324e
Revises: 
Create Date: 2024-07-13 08:02:28.601234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9176ecf6324e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tbl_obj = op.create_table('TB_bk_기관코드',
    sa.Column('seq', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Code', sa.NVARCHAR(length=100, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('기관명칭', sa.NVARCHAR(length=100, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('seq', name='PK__TB_bk__DDDFBCBEB28ABD14')
    )

    op.bulk_insert(
            tbl_obj,
            [
                {'Code':'0001','기관명칭':'국민은행' }
                ]
            )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('TB_bk_기관코드')
    # ### end Alembic commands ###
