SHOW VARIABLES LIKE '%version%';  
USE mysql;
create user starshorse ;
create user starshorse@localhost identified by '1234';
-- create user starshorse@'%' identified by '1234';
grant all privileges on *.* to starshorse@localhost idnetified by '1234';
flush privileges;
show grants for starshorse@localhost;
SELECT User, Host, plugin FROM mysql.user;
select user , host, plugin from user; 
exit;
