"""Init

Revision ID: 3915171d01ce
Revises: 
Create Date: 2025-01-19 10:11:34.549216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
import datetime

# revision identifiers, used by Alembic.
revision = '3915171d01ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tbl_obj = op.create_table('TB_고객서비스_codeFApi',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('서비스명', sa.String(length=120), nullable=True),
    sa.Column('db_name', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.bulk_insert(
            tbl_obj ,
            [{
                "서비스명":"계좌거래목록",
                "db_name":"ezoffice",
                "enabled": 1 ,
                "date": datetime.datetime.now() 
                }]
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TB_고객서비스_codeFApi')
    # ### end Alembic commands ###
