"""empty message

Revision ID: 751397b41107
Revises: 
Create Date: 2024-07-06 14:44:42.919678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751397b41107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VW_stock_mine')
    with op.batch_alter_table('sample-sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sample-sales_index')

    op.drop_table('sample-sales')
    op.drop_table('매매일지')
    op.drop_table('low_pbr_high_div')
    op.drop_table('VW_stock_mine_basics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VW_stock_mine_basics',
    sa.Column('회사명', sa.NVARCHAR(length=30, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('종목코드', sa.NVARCHAR(length=6, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('업종', sa.NVARCHAR(collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('주요제품', sa.NVARCHAR(length=100, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('상장일', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('결산월', sa.NVARCHAR(length=5, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('대표자명', sa.NVARCHAR(collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('홈페이지', sa.NVARCHAR(collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('지역', sa.NVARCHAR(length=10, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('low_pbr_high_div',
    sa.Column('종목코드', sa.NVARCHAR(length=6, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('종목명', sa.NVARCHAR(length=15, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('종가', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('EPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PER', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('선행_EPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('선행_PER', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=True),
    sa.Column('BPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PBR', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('주당배당금', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('배당수익률', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False)
    )
    op.create_table('매매일지',
    sa.Column('순번', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('종목', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('코드', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('업종', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('날짜', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('수량', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('매수매도가', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('매수_매도', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('코스피', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('삼성전자', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('요일', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('sample-sales',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('account number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit price', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('ext price', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATETIME(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('sample-sales', schema=None) as batch_op:
        batch_op.create_index('ix_sample-sales_index', ['index'], unique=False)

    op.create_table('VW_stock_mine',
    sa.Column('종목명', sa.NVARCHAR(length=14, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('종목코드', sa.NVARCHAR(length=6, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PER', sa.NVARCHAR(length=8, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PBR', sa.NVARCHAR(length=5, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('배당수익률', sa.NVARCHAR(length=5, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
