set nocompatible
set number
filetype on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  Plugin 'VundleVim/Vundle.vim'     
  Plugin 'preservim/nerdtree'
  Plugin 'pangloss/vim-javascript'
  Plugin 'vim-airline/vim-airline'
  Plugin 'tpope/vim-fugitive'
  Plugin 'isRuslan/vim-es6'
#!플러그인 목록에 Vundle 추가
call vundle#end()

nmap <F5> :NERDTreeToggle<CR>

