var web2dbCov =  {'No': 'idx',
//  'lastNo': ,
//  'lastTrackId': ,
// '분류':  0;   //  ,
// 'trackId':2020082001 ; // ,
 'clientCompany': 'company',
 'clientOwner': 'user',
 'clientMRO': 'mro',
//  'ezOwner': ,
 '재견적': 'c_re_request_count',
//  'CreateOwner': ,
 '견적요청일': 'c_requested_time',
//  '견적회신일': ,
//  '견적만료일': ,
 'Supplier': 'c_maker',
//  'Cas No Changed': ,
//  'Name Changed': ,
//  'Cat No Changed': ,
//  'Unit Changed': ,
//  'ea Changed': ,
//  'purity Changed': ,
 'Cas No': 'c_cas_no',
 'Name': 'c_chemical_name',
 'Cat No': 'c_cat_no',
 'Unit': 'c_unit',
 'ea': 'c_qty',
 'Cas No Ez': 'o_cas_no',
 'Name Ez': 'o_chemical_name',
 'Cat No Ez': 'o_cat_no',
 'Unit Ez': 'o_unit',
 'ea Ez': 'o_qty',
 'Cas No Supplier': 'm_cas_no',
 'Name Supplier': 'm_chemical_name',
 'Cat No Supplier': 'm_cat_no',
 'Unit Supplier': 'm_unit',
 'ea Supplier': 'm_qty',
//  '요청수신일': ,
//  '가격(VAT별도)': ,
 'purity': 'c_purity',
//  '비고': ,
 'Currency': 'm_currency',
//  'Currency Rate': ,
 'Price': 'm_price',
 'Handling Fee': 'm_handling_fee',
 'Shipping Fee': 'm_shipping_fee',
 'Other Charges': 'm_other_charges',
 'Purity Over': 'c_is_purity_greater',
 'purity Ez': 'o_purity',
 'purity Supplier': 'm_purity',
//  'Purity %': ,
//  'purity Ez%': ,
//  'purity Supplier%': ,
 'Remark Client': 'c_remark',
 'Remark Operator': 'o_remark',
 'Remark Supplier': 'm_remark',
 'sameType': 'm_is_same_product',
//  'supplierAvailable': ,
 'dangerousGood': 'm_is_dg',
 'airShipping': 'm_is_air_shipping',
//  'Stock/Lead Time': ,
 'Stock Status': 'm_stock_status',
 'Country of Origin': 'm_origin_country',
 'Country of Shipment': 'm_shipment_country',
 '계약번호': 'o_contract_no' }


