# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCompfnguidecom():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_compfnguidecom(self):
    self.driver.get("https://comp.fnguide.com/SVO2/ASP/SVD_idxRank.asp?pGB=1&gicode=A005930&cID=&MenuYn=Y&ReportGB=&NewMenuID=302&stkGb=701")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.ID, "selUpjong").click()
    dropdown = self.driver.find_element(By.ID, "selUpjong")
    dropdown.find_element(By.XPATH, "//option[. = '전체']").click()
    self.driver.find_element(By.ID, "btnSearch").click()
    self.driver.find_element(By.LINK_TEXT, "Download").click()
  
