// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('EZchemtech_newApp', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('EZchemtech_newApp', async function() {
    // Test name: EZchemtech_newApp
    // Step # | name | target | value
    // 1 | open | /homepage/ | 
    await driver.get("http://34.64.240.149:3004/homepage/")
    // 2 | setWindowSize | 1689x728 | 
    await driver.manage().window().setRect({ width: 1689, height: 728 })
    // 3 | click | css=#menu-community > .item | 
    await driver.findElement(By.css("#menu-community > .item")).click()
    // 4 | click | id=email_address | 
    await driver.findElement(By.id("email_address")).click()
    // 5 | type | id=email_address | star_horse@naver.com
    await driver.findElement(By.id("email_address")).sendKeys("star_horse@naver.com")
    // 6 | type | id=password | ch1whdrb
    await driver.findElement(By.id("password")).sendKeys("ch1whdrb")
    // 7 | click | css=.btn-info | 
    await driver.findElement(By.css(".btn-info")).click()
    // 8 | click | css=.form-group:nth-child(4) .btn | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 9 | selectWindow | handle=${win1141} | 
    await driver.findElement(By.css(".form-group:nth-child(4) .btn")).click()
    // 10 | click | linkText=Design[collections] | 
    vars["win1141"] = await waitForWindow(2000)
    // 11 | click | css=#sidebarCollapse > span | 
    await driver.switchTo().window(vars["win1141"])
    // 12 | click | linkText=#[NEW App] | 
    await driver.findElement(By.linkText("Design[collections]")).click()
    // 13 | click | id=app_name | 
    await driver.findElement(By.css("#sidebarCollapse > span")).click()
    // 14 | type | id=app_name | 1234
    await driver.findElement(By.linkText("#[NEW App]")).click()
    // 15 | click | css=.btn-secondary | 
    await driver.findElement(By.id("app_name")).click()
    await driver.findElement(By.id("app_name")).sendKeys("1234")
    await driver.findElement(By.css(".btn-secondary")).click()
  })
})
