# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("https://member.paxnet.co.kr/rpan/member/login?returnURL=http%3A%2F%2Fwww.paxnet.co.kr%2Fitem%2Flike%2FmyLike?url=null")
    self.driver.set_window_size(1272, 440)
    self.driver.find_element(By.ID, "passwd").click()
    self.driver.find_element(By.ID, "passwd").send_keys("ch1whdrb")
    self.driver.find_element(By.CSS_SELECTOR, ".red:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_nickNm:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "My").click()
    self.driver.find_element(By.LINK_TEXT, "관심종목").click()
    self.driver.execute_script("window.scrollTo(0,35.20000076293945)")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .text").click()
    dropdown = self.driver.find_element(By.ID, "groupCode")
    dropdown.find_element(By.XPATH, "//option[. = '보유종목[중소형]']").click()
  
