"""KORSP_tbls

Revision ID: 428b91cece37
Revises: 
Create Date: 2024-02-12 08:52:00.223502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428b91cece37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VW_stock_mine',
    sa.Column('종목명', sa.Unicode(length=14), nullable=True),
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.Column('PER', sa.Unicode(length=8), nullable=True),
    sa.Column('PBR', sa.Unicode(length=5), nullable=True),
    sa.Column('배당수익률', sa.Unicode(length=5), nullable=True)
    )
    op.create_table('VW_stock_mine_basics',
    sa.Column('회사명', sa.Unicode(length=30), nullable=True),
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.Column('업종', sa.Unicode(), nullable=True),
    sa.Column('주요제품', sa.Unicode(length=100), nullable=True),
    sa.Column('상장일', sa.Date(), nullable=True),
    sa.Column('결산월', sa.Unicode(length=5), nullable=True),
    sa.Column('대표자명', sa.Unicode(), nullable=True),
    sa.Column('홈페이지', sa.Unicode(), nullable=True),
    sa.Column('지역', sa.Unicode(length=10), nullable=True)
    )
    op.create_table('low_pbr_high_div',
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.Column('종목명', sa.Unicode(length=15), nullable=False),
    sa.Column('종가', sa.Integer(), nullable=False),
    sa.Column('EPS', sa.Integer(), nullable=True),
    sa.Column('PER', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('선행_EPS', sa.Integer(), nullable=True),
    sa.Column('선행_PER', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('BPS', sa.Integer(), nullable=True),
    sa.Column('PBR', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('주당배당금', sa.Integer(), nullable=False),
    sa.Column('배당수익률', sa.Numeric(precision=5, scale=2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('low_pbr_high_div')
    op.drop_table('VW_stock_mine_basics')
    op.drop_table('VW_stock_mine')
    # ### end Alembic commands ###
