"""KORSP_tbls_2

Revision ID: d885ca431430
Revises: 428b91cece37
Create Date: 2024-02-12 09:56:03.963384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd885ca431430'
down_revision: Union[str, None] = '428b91cece37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mine',
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.PrimaryKeyConstraint('종목코드')
    )
    op.create_table('pykrx_time',
    sa.Column('일자', sa.Date(), nullable=False),
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.Column('종목명', sa.Unicode(length=14), nullable=False),
    sa.Column('관리여부', sa.Unicode(length=4), nullable=True),
    sa.Column('PER', sa.Unicode(length=8), nullable=True),
    sa.Column('PBR', sa.Unicode(length=5), nullable=True),
    sa.Column('배당수익률', sa.Unicode(length=5), nullable=True)
    )
    op.create_table('stables',
    sa.Column('일자', sa.Date(), nullable=False),
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.Column('종목명', sa.Unicode(length=14), nullable=False),
    sa.Column('관리여부', sa.Unicode(length=4), nullable=False),
    sa.Column('종가', sa.Unicode(length=9), nullable=False),
    sa.Column('EPS', sa.Unicode(length=7), nullable=False),
    sa.Column('PER', sa.Unicode(length=8), nullable=False),
    sa.Column('BPS', sa.Unicode(length=9), nullable=False),
    sa.Column('PBR', sa.Unicode(length=5), nullable=False),
    sa.Column('주당배당금', sa.Unicode(length=6), nullable=True),
    sa.Column('배당수익률', sa.Unicode(length=5), nullable=True),
    sa.PrimaryKeyConstraint('종목코드')
    )
    op.create_table('stables_nw',
    sa.Column('종목코드', sa.Unicode(length=6), nullable=False),
    sa.Column('종목명', sa.Unicode(length=15), nullable=False),
    sa.Column('종가', sa.Integer(), nullable=False),
    sa.Column('대비', sa.Integer(), nullable=False),
    sa.Column('등락률', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('EPS', sa.Integer(), nullable=True),
    sa.Column('PER', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('선행_EPS', sa.Integer(), nullable=True),
    sa.Column('선행_PER', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('BPS', sa.Integer(), nullable=True),
    sa.Column('PBR', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('주당배당금', sa.Integer(), nullable=False),
    sa.Column('배당수익률', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('종목코드')
    )
    """
    op.drop_table('VW_stock_mine_basics')
    op.drop_table('매매일지')
    op.drop_table('VW_stock_mine')
    op.drop_table('low_pbr_high_div')
    """
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_table('low_pbr_high_div',
    sa.Column('종목코드', sa.NVARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('종목명', sa.NVARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('종가', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('EPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PER', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('선행_EPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('선행_PER', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=True),
    sa.Column('BPS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PBR', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('주당배당금', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('배당수익률', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False)
    )
    op.create_table('VW_stock_mine',
    sa.Column('종목명', sa.NVARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('종목코드', sa.NVARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('PER', sa.NVARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('PBR', sa.NVARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('배당수익률', sa.NVARCHAR(length=5), autoincrement=False, nullable=True)
    )
    op.create_table('매매일지',
    sa.Column('순번', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('종목', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('코드', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('업종', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('날짜', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('수량', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('매수매도가', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('매수_매도', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('코스피', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('삼성전자', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('요일', sa.VARCHAR(length=512, collation='Korean_Wansung_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('VW_stock_mine_basics',
    sa.Column('회사명', sa.NVARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('종목코드', sa.NVARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('업종', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('주요제품', sa.NVARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('상장일', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('결산월', sa.NVARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('대표자명', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('홈페이지', sa.NVARCHAR(), autoincrement=False, nullable=True),
    sa.Column('지역', sa.NVARCHAR(length=10), autoincrement=False, nullable=True)
    )
    """
    op.drop_table('stables_nw')
    op.drop_table('stables')
    op.drop_table('pykrx_time')
    op.drop_table('mine')
    # ### end Alembic commands ###
